Initial implementation of ROCK5B platform and RK3588 SOC
RadxaYuntian/wiringX pull request #8
Opened 2023-11-14 08:26 UTC by nascs

2023-11-16 06:36 UTC, RadxaYuntian requested changes

2023-11-16 06:36 UTC, RadxaYuntian commented on docs/source/platforms/radxa/rock5b.rst
> +| 5v | 5v | 0v | 15 | 16 | 1 | 0v | 4 | 5  | 0v | -1  | 10 | 11 | 31 | 0v | 26 | 0v | 27 | 28 | 29 |
0v->GND
-1->NA

2023-11-16 06:36 UTC, RadxaYuntian commented on src/platform/radxa/rock5b.c
> +			113,			109,			111,			112,
tab宽度为8对齐

2023-11-16 06:36 UTC, RadxaYuntian commented on src/platform/radxa/rock5b.c
> +	rock5b->soc->setMap(map,_sizeof(map));
```suggestion
	rock5b->soc->setMap(map, _sizeof(map));
```
函数调用逗号后面空格

2023-11-16 06:36 UTC, RadxaYuntian commented on src/platform/radxa/rock5b.h
> +#endif
缺少结尾空行

2023-11-16 06:36 UTC, RadxaYuntian commented on src/soc/rockchip/rk3588.c
> +  for (int i = 0; i < GPIO_BANK_COUNT; i++) {
tab缩进

2023-11-16 06:36 UTC, RadxaYuntian commented on src/soc/rockchip/rk3588.c
太多rk3399.c的重复代码了，可以把两者合并

2023-11-16 06:36 UTC, RadxaYuntian commented on src/soc/rockchip/rk3588.c
> +	{"GPIO0_A0", 0, 0, {PMU1CRU_GATE_CON05, 5}, {PMU1_IOC_GPIO0A_IOMUX_SEL_L,  0}, {GPIO_SWPORT_DDR_L,  0}, {GPIO_SWPORT_DR_L,  0}, {GPIO_EXT_PORT,  0}, FUNCTION_DIGITAL, PINMODE_NOT_SET, 0},
这些应该都可以用宏来生成

2023-11-20 10:22 UTC, RadxaYuntian requested changes

2023-11-20 10:22 UTC, RadxaYuntian commented on src/soc/rockchip/common.c
> +#include "common.h"
少了文件抬头

2023-11-20 10:22 UTC, RadxaYuntian commented on src/soc/rockchip/common.h
> +#ifndef COMMON_H
```suggestion
#ifndef __WIRINGX_SOC_ROCKCHIP_COMMON_H__
```
万一你这个文件被别人引用了，然后他也有个common.h呢？

2023-11-20 10:22 UTC, RadxaYuntian commented on src/soc/rockchip/common.h
1. 少了文件抬头
2. 多余空行

2023-11-20 10:22 UTC, RadxaYuntian commented on src/soc/rockchip/common.h
> +
```suggestion
```

2023-11-20 10:22 UTC, RadxaYuntian commented on src/soc/rockchip/common.h
> +// extern inline const uintptr_t gpio_register_physical_address[MAX_REG_AREA];
```suggestion
```
不要提交注释掉的代码

2023-11-20 10:22 UTC, RadxaYuntian commented on src/soc/rockchip/common.h
> +
```suggestion
```

2023-11-20 10:22 UTC, RadxaYuntian commented on src/soc/rockchip/common.h
> +struct grf_t{
```suggestion

struct grf_t{
```

2023-11-20 10:22 UTC, RadxaYuntian commented on src/soc/rockchip/common.h
> +struct direction_t{
```suggestion

struct direction_t{
```

2023-11-20 10:22 UTC, RadxaYuntian commented on src/soc/rockchip/common.h
> +#endif
这个一般是放在`#ifndef __WIRINGX_SOC_ROCKCHIP_COMMON_H__`之后，包含整个文件的

2023-11-20 10:22 UTC, RadxaYuntian commented on src/soc/rockchip/common.h
> +	int rockchipSetup(struct soc_t *rockchip_soc);
函数定义不用缩进

2023-11-20 10:22 UTC, RadxaYuntian commented on src/soc/rockchip/common.h
> +#define COMMON_LAYOUT_T \
直接定一个新的struct啊，然后有几种处理变种类型的方法：
1. 每个类型特殊的部分定义成额外struct，然后在基类型里使用union把他们都包括起来，同时需要有方法识别集类型所使用的union
2. 额外部分在基类型后面接着添加，基类型额外带一个版本号，通过版本号识别哪些field是可以访问的

2023-11-20 10:22 UTC, RadxaYuntian commented on src/soc/rockchip/rk3588.c
> +static char *rk3588GetPinName(int pin) {
这种可以用宏定义

2023-11-21 11:18 UTC, nascs commented on src/soc/rockchip/common.h
> +#define COMMON_LAYOUT_T \
昨天没注意，刚刚看到

2023-11-21 11:20 UTC, nascs commented on src/platform/radxa/rock5b.c
> +			113,			109,			111,			112,
wiringX 的缩进宽度好像是 2 ?

2023-11-21 11:33 UTC, RadxaYuntian commented on src/platform/radxa/rock5b.c
> +			113,			109,			111,			112,
全文搜索了一下，是4

2023-11-22 08:24 UTC, RadxaYuntian requested changes

2023-11-22 08:24 UTC, RadxaYuntian commented on src/soc/rockchip/rk3588.c
> +		REGISTER_CLEAR_BITS(out_reg, pin->out.bit, 2);
为什么set high只有1位，low有2位？

2023-11-22 08:24 UTC, RadxaYuntian commented on src/soc/rockchip/rk3588.c
> +		REGISTER_CLEAR_BITS(dir_reg, pin->direction.bit, 2);
为什么set output只有1位，input有2位？

2023-11-27 08:29 UTC, nascs commented on src/soc/rockchip/rk3588.c
> +		REGISTER_CLEAR_BITS(dir_reg, pin->direction.bit, 2);
可以设置 1

2023-11-27 09:31 UTC, nascs commented on src/soc/rockchip/rk3588.c
> +		REGISTER_CLEAR_BITS(dir_reg, pin->direction.bit, 2);
可以设置 size 为 1

2023-12-04 06:39 UTC, RadxaYuntian requested changes

2023-12-04 06:39 UTC, RadxaYuntian commented on src/platform/radxa/common.c
缩进要统一，这里有的是空格有的是tab

2023-12-04 06:39 UTC, RadxaYuntian commented on src/platform/radxa/rock5b.c
这里的空格/tab也乱七八糟

2023-12-04 06:39 UTC, RadxaYuntian commented on src/platform/radxa/rock4.c
> +	radxaValidGPIO(pin, map, _sizeof(map));
```suggestion
	return radxaValidGPIO(pin, map, _sizeof(map));
```

2023-12-04 06:39 UTC, RadxaYuntian commented on src/platform/radxa/rock5b.c
> +	radxaValidGPIO(pin, map, _sizeof(map));
```suggestion
	return radxaValidGPIO(pin, map, _sizeof(map));
```

2023-12-04 06:39 UTC, RadxaYuntian commented on src/platform/radxa/common.c
> +        return 0;
```suggestion
```
直接利用下面的return ret

2023-12-04 06:39 UTC, RadxaYuntian commented on src/platform/radxa/common.c
> +    return 0;
```suggestion
    return (pin < 0 || pin >= map_count || map[pin] == -1) ? -1 : 0;
```
可以用三元运算符简化

2023-12-04 06:39 UTC, RadxaYuntian commented on src/soc/rockchip/rk3399.c
> +	struct layout_t *pin = NULL;;
```suggestion
	struct layout_t *pin = NULL;
```

2023-12-05 08:57 UTC, RadxaYuntian requested changes
改完了在3399和3588上都测试一遍，避免像之前合并后才发现功能异常

2023-12-05 08:57 UTC, RadxaYuntian commented on src/platform/radxa/rock4.c
> -
这里不用删除

2023-12-05 08:57 UTC, RadxaYuntian commented
可以整理commit准备提交给上游了

2023-12-06 03:59 UTC, RadxaYuntian approved these changes
历史整理一下，然后在两个平台上测试一下

2023-12-11 04:03 UTC, RadxaYuntian requested changes

2023-12-11 04:03 UTC, RadxaYuntian commented on src/soc/rockchip/rk3399.c
> +	rk3399->page_size = (1024*32);
没有32k的页面，看看为什么sysconf没有返回正确的值

2023-12-11 10:07 UTC, nascs commented
在 4B + 上测了一下，功能正常

2023-12-11 10:13 UTC, RadxaYuntian commented
把commit历史整理一下

2023-12-13 02:30 UTC, RadxaYuntian requested changes
rebase一下，修改commit顺序：
首先是08bbb1b5b5e12762350496348c98edf2b9059242
然后是f8b06c10f39e35a1223369fb48bdc6c9062ac8d9
6838d79685d8486c70e357e0f7629244976c822d和上面的commit合并，没有留着的必要

2023-12-13 07:37 UTC, RadxaYuntian requested changes

2023-12-13 07:37 UTC, RadxaYuntian commented on src/platform/radxa/common.c
> +}
缺少结尾空行

2023-12-13 07:37 UTC, RadxaYuntian commented on src/platform/radxa/common.c
这些rock 4/rk3399的修改要放到上一个commit里面

2023-12-15 07:29 UTC, RadxaYuntian commented
可以给上游提pr了

2023-12-15 07:29 UTC, closed without merging