Milkv duo upstream
RadxaYuntian/wiringX pull request #9
Opened 2024-03-08 02:54 UTC by willian-milk

2024-03-08 06:44 UTC, RadxaYuntian requested changes

2024-03-08 06:44 UTC, RadxaYuntian commented on docs/source/platforms/milkv/duo.rst
> +| System on Chip | Sophgo cv1800b  |
```suggestion
| System on Chip | Sophgo CV1800B  |
```
要符合别人的产品名

2024-03-08 06:44 UTC, RadxaYuntian commented on docs/source/platforms/milkv/duo.rst
> +| 0  | 1  | 0v | 2  | 3  | 4  | 5  | 0v | 6  | 7  | 8  | 9  | 0v | 10 | 11 | 12 | 13 | 0v |3.3v| 15 | N/A | 25  |
1. 0和0v容易混淆，0v改成GND
2. v作为单位要大写
3. 补上右边的USB引脚说明，中间的单元留空就好

2024-03-08 06:44 UTC, RadxaYuntian commented on docs/source/platforms/milkv/duo.rst
> +Note: No. 25 is the user LED.
```suggestion
Note: GPIO 25 is also connected to the User LED.
```

2024-03-08 06:44 UTC, RadxaYuntian commented on docs/source/platforms/milkv/index.rst
> +MilkV
```suggestion
Milk-V
```
要符合我们的公司名

2024-03-08 06:44 UTC, RadxaYuntian commented on docs/source/platforms/milkv/duo.rst
> +MilkV DUO
```suggestion
Milk-V Duo
```
https://milkv.io/duo

2024-03-08 06:44 UTC, RadxaYuntian commented on src/platform/milkv/duo.c
> +  Copyright (c) 2023 MilkV Ltd.
```suggestion
  Copyright (c) 2024 Shenzhen MilkV Technology Co., Ltd
```
https://milkv.io/

2024-03-08 06:44 UTC, RadxaYuntian commented on src/platform/milkv/duo.c
> +	        Carbon <carbon@milkv.io>
缩进又是tab又是空格，统一一下

2024-03-08 06:44 UTC, RadxaYuntian commented on src/platform/milkv/duo.h
> +#ifndef __WIRINGX_DUO_H_
```suggestion
#ifndef __WIRINGX_MILKV_DUO_H_
```
只准你叫Duo么？

2024-03-08 06:44 UTC, RadxaYuntian commented on src/platform/milkv/duo.h
> +extern struct platform_t *duo;
```suggestion
extern struct platform_t *milkv_duo;
```

2024-03-08 06:44 UTC, RadxaYuntian commented on src/soc/sophgo/cv180.c
cv180x.c才是正确的soc家族名

2024-03-08 07:22 UTC, nascs commented on src/platform/milkv/duo.c
> +	        Carbon <carbon@milkv.io>
仔细看了一下，他大多数文件头部都是 copyright 那行一个 tab，然后其他行是空格

2024-03-08 07:24 UTC, RadxaYuntian commented on src/platform/milkv/duo.c
> +	        Carbon <carbon@milkv.io>
其他行如果不是有额外缩进就用tab,有额外缩进统一用space

2024-03-08 07:24 UTC, RadxaYuntian commented on src/platform/milkv/duo.c
> +	        Carbon <carbon@milkv.io>
他的tab宽度是2

2024-03-08 07:24 UTC, RadxaYuntian commented on src/platform/milkv/duo.c
> +	        Carbon <carbon@milkv.io>
干脆copyright都用空格缩进吧，代码部分才tab缩进

2024-03-11 07:29 UTC, RadxaYuntian commented on docs/source/platforms/milkv/duo.rst
> +| 0  | 1  | 0v | 2  | 3  | 4  | 5  | 0v | 6  | 7  | 8  | 9  | 0v | 10 | 11 | 12 | 13 | 0v |3.3v| 15 | N/A | 25  |
3没有处理

2024-03-11 07:29 UTC, RadxaYuntian commented on docs/source/platforms/milkv/duo.rst
> +MilkV DUO
没有处理

2024-03-11 07:29 UTC, RadxaYuntian commented on src/platform/milkv/duo.c
> +	        Carbon <carbon@milkv.io>
没有处理

2024-03-11 07:38 UTC, RadxaYuntian requested changes

2024-03-11 07:38 UTC, RadxaYuntian commented on python/setup.py
> +			'../src/soc/sophgo/cv180.c',
```suggestion
			'../src/soc/sophgo/cv180x.c',
```

2024-03-11 07:38 UTC, RadxaYuntian commented on python/wiringX/wiringx.c
> +	PyModule_AddObject(module, "DUO", Py_BuildValue("s", "duo"));
```suggestion
	PyModule_AddObject(module, "DUO", Py_BuildValue("s", "milkv_duo"));
```

2024-03-11 07:38 UTC, RadxaYuntian commented on src/platform/milkv/duo.c
> +	   	8,			9,			10,			11,
怎么上面和下面的缩进不一致

2024-03-11 07:38 UTC, RadxaYuntian commented on src/platform/milkv/duo.c
> +	milkv_duo->soc = soc_get("Sophgo", "CV180");
```suggestion
	milkv_duo->soc = soc_get("Sophgo", "CV180X");
```
改了代码都不测试一下么

2024-03-11 07:38 UTC, RadxaYuntian commented on src/soc/sophgo/cv180x.c
> +	sprintf(path, "/sys/class/gpio/gpio%d", pin->num);
你上面是用寄存器操作，这里用gpiod能正常工作么？

2024-03-11 07:38 UTC, RadxaYuntian commented on src/soc/sophgo/cv180x.c
> +	{"XGPIOC_24",   2, 440, {0x112c, 0x3}, {GPIO_SWPORTA_DDR, 24}, {GPIO_SWPORTA_DR, 24}, FUNCTION_DIGITAL, PINMODE_NOT_SET, 0}, /* GP25 */
你这里还是要按顺序定义全整个SoC的GPIO,不然别的产品怎么办

2024-03-11 09:42 UTC, willian-milk commented on src/soc/sophgo/cv180x.c
> +	{"XGPIOC_24",   2, 440, {0x112c, 0x3}, {GPIO_SWPORTA_DDR, 24}, {GPIO_SWPORTA_DR, 24}, FUNCTION_DIGITAL, PINMODE_NOT_SET, 0}, /* GP25 */
当时是因为给的寄存器不全

2024-03-11 10:39 UTC, RadxaYuntian commented on src/soc/sophgo/cv180x.c
> +	{"XGPIOC_24",   2, 440, {0x112c, 0x3}, {GPIO_SWPORTA_DDR, 24}, {GPIO_SWPORTA_DR, 24}, FUNCTION_DIGITAL, PINMODE_NOT_SET, 0}, /* GP25 */
现在都有了么？另外明显很多缺少的gpio可以推导出来

2024-03-11 11:26 UTC, willian-milk commented on src/soc/sophgo/cv180x.c
> +	{"XGPIOC_24",   2, 440, {0x112c, 0x3}, {GPIO_SWPORTA_DDR, 24}, {GPIO_SWPORTA_DR, 24}, FUNCTION_DIGITAL, PINMODE_NOT_SET, 0}, /* GP25 */
开放的 GPIO 信息，只有它工具列出来的 80 个左右，去除没有 GPIO 功能的 IO, 可能就六七十个左右

2024-03-11 11:35 UTC, willian-milk commented on src/soc/sophgo/cv180x.c
> +	{"XGPIOC_24",   2, 440, {0x112c, 0x3}, {GPIO_SWPORTA_DDR, 24}, {GPIO_SWPORTA_DR, 24}, FUNCTION_DIGITAL, PINMODE_NOT_SET, 0}, /* GP25 */
还有一个考虑是之前是说要和 duo 的物理引脚对其来着，原来是按照 wiringX 的那种引脚顺序来的，后面专门改过来了，https://milkv.io/zh/docs/duo/application-development/wiringx

2024-03-12 02:45 UTC, RadxaYuntian commented on src/soc/sophgo/cv180x.c
> +	{"XGPIOC_24",   2, 440, {0x112c, 0x3}, {GPIO_SWPORTA_DDR, 24}, {GPIO_SWPORTA_DR, 24}, FUNCTION_DIGITAL, PINMODE_NOT_SET, 0}, /* GP25 */
> 开放的 GPIO 信息，只有它工具列出来的 80 个左右，去除没有 GPIO 功能的 IO, 可能就六七十个左右

那就只用开放的信息吧

> 还有一个考虑是之前是说要和 duo 的物理引脚对其来着，原来是按照 wiringX 的那种引脚顺序来的，后面专门改过来了，https://milkv.io/zh/docs/duo/application-development/wiringx

你猜猜wiringx会不会同意用你板级gpio顺序来覆盖soc原生gpio顺序

2024-03-12 02:49 UTC, RadxaYuntian commented on src/soc/sophgo/cv180x.c
> +	{"XGPIOC_24",   2, 440, {0x112c, 0x3}, {GPIO_SWPORTA_DDR, 24}, {GPIO_SWPORTA_DR, 24}, FUNCTION_DIGITAL, PINMODE_NOT_SET, 0}, /* GP25 */
你应该只需要把static int map[]弄好就可以把gpio编号弄成你想要的

2024-03-12 02:52 UTC, RadxaYuntian commented on src/soc/sophgo/cv180x.c
> +	{"XGPIOC_24",   2, 440, {0x112c, 0x3}, {GPIO_SWPORTA_DDR, 24}, {GPIO_SWPORTA_DR, 24}, FUNCTION_DIGITAL, PINMODE_NOT_SET, 0}, /* GP25 */
![image](https://github.com/RadxaYuntian/wiringX/assets/95260730/cc72ed34-ae34-4384-85e6-3c7d664b952d)
https://wiki.odroid.com/odroid-c1/hardware/expansion_connectors
别人odroid c1就应该是正确的

2024-03-12 06:38 UTC, RadxaYuntian requested changes

2024-03-12 06:38 UTC, RadxaYuntian commented on src/soc/sophgo/cv180x.c
> +	printf("pin-name: %s\n", pin->name);
不要提交调试代码

2024-03-12 06:38 UTC, RadxaYuntian commented on src/platform/milkv/duo.c
> +			17,			18,			64,			63,
这个和注释的缩进感觉不匹配吧，另外确认了不影响wiringx的编号对吧？

2024-03-12 07:36 UTC, willian-milk commented on src/platform/milkv/duo.c
> +			17,			18,			64,			63,
测试过了，这编号和 [duo 的文档](https://milkv.io/zh/docs/duo/application-development/wiringx)保持一致

2024-03-12 08:30 UTC, RadxaYuntian commented on docs/source/platforms/milkv/duo.rst
> +MilkV DUO
没有处理

2024-03-12 08:30 UTC, RadxaYuntian commented on docs/source/platforms/milkv/duo.rst
> +| 0  | 1  | 0v | 2  | 3  | 4  | 5  | 0v | 6  | 7  | 8  | 9  | 0v | 10 | 11 | 12 | 13 | 0v |3.3v| 15 | N/A | 25  |
3没有处理

2024-03-12 08:33 UTC, willian-milk commented on python/setup.py
> +			'../src/soc/sophgo/cv180.c',
这个已处理

2024-03-12 08:33 UTC, willian-milk commented on python/wiringX/wiringx.c
> +	PyModule_AddObject(module, "DUO", Py_BuildValue("s", "duo"));
已处理

2024-03-12 08:34 UTC, willian-milk commented on src/platform/milkv/duo.c
> +	milkv_duo->soc = soc_get("Sophgo", "CV180");
已处理

2024-03-12 08:34 UTC, willian-milk commented on src/soc/sophgo/cv180x.c
> +	printf("pin-name: %s\n", pin->name);
已处理

2024-03-12 08:36 UTC, RadxaYuntian requested changes

2024-03-12 08:36 UTC, RadxaYuntian commented on src/platform/milkv/duo.c
> +			-1,			-1,			-1,			-1
没有的还写出来？

2024-03-12 08:36 UTC, RadxaYuntian commented on src/platform/milkv/duo.c
> +static int duoValidGPIO(int pin) {
```suggestion
static int milkv_duoValidGPIO(int pin) {
```
函数前缀保持一致

2024-03-12 08:36 UTC, RadxaYuntian commented on src/soc/sophgo/cv180x.c
> +	{"XGPIOA_14", 0, 494, {0x1c, 0x3}, {GPIO_SWPORTA_DDR, 14}, {GPIO_SWPORTA_DR, 14}, FUNCTION_DIGITAL, PINMODE_NOT_SET, 0}, /* GP14 */
```suggestion
	{"XGPIOA_14", 0, 494, {0x1c, 0x3}, {GPIO_SWPORTA_DDR, 14}, {GPIO_SWPORTA_DR, 14}, FUNCTION_DIGITAL, PINMODE_NOT_SET, 0},
```
你这个注释跟cv180x SoC毫无关系，不要放进来

2024-03-12 08:36 UTC, RadxaYuntian commented on src/soc/sophgo/cv180x.c
> +	sprintf(path, "/sys/class/gpio/gpio%d", pin->num);
没有回复

2024-03-12 08:45 UTC, willian-milk commented on src/soc/sophgo/cv180x.c
> +	sprintf(path, "/sys/class/gpio/gpio%d", pin->num);
这里有这个 path 是因为 wiringX 中断通过 sysFS 来触发的

2024-03-12 09:05 UTC, willian-milk commented on docs/source/platforms/milkv/duo.rst
> +| 0  | 1  | 0v | 2  | 3  | 4  | 5  | 0v | 6  | 7  | 8  | 9  | 0v | 10 | 11 | 12 | 13 | 0v |3.3v| 15 | N/A | 25  |
把 15 和 25 之间的 N/A 去掉改成同样空间的空格？就是和 [duo 的 wiringX 文档 ](https://milkv.io/zh/docs/duo/application-development/wiringx) 保持一致 ?

2024-03-12 09:35 UTC, RadxaYuntian commented on src/soc/sophgo/cv180x.c
> +	sprintf(path, "/sys/class/gpio/gpio%d", pin->num);
好吧，这就留给wiringX去关心了

2024-03-12 09:37 UTC, RadxaYuntian commented on docs/source/platforms/milkv/duo.rst
> +MilkV DUO
我都给你写好了首字母大写怎么还是写错了……

2024-03-12 09:38 UTC, RadxaYuntian commented on src/platform/milkv/duo.c
> +			-1,			-1,			-1,			-1
不是你这最后4个都是-1没法用啊，干嘛定义他们？

2024-03-12 09:40 UTC, RadxaYuntian requested changes

2024-03-12 09:40 UTC, RadxaYuntian commented on docs/source/platforms/milkv/duo.rst
> +| 0  | 1  | GND | 2  | 3  | 4  | 5  | GND | 6  | 7  | 8  | 9  | GND | 10 | 11 | 12 | 13 | GND | 14 | 15 |     | 25  |
改空格都没改全……我的意思是写成7列中间2-6列最右边标记以太网(?)那5个pin，然后中间留空。但既然文档都没标那就算了
空格还是改回N/A吧，看的清楚点

2024-03-13 07:00 UTC, RadxaYuntian requested changes

2024-03-13 07:00 UTC, RadxaYuntian commented on src/soc/sophgo/cv180x.h
> +#define __WIRINGX_CV180_H
```suggestion
#ifndef __WIRINGX_CV180X_H
#define __WIRINGX_CV180X_H
```

2024-03-13 07:00 UTC, RadxaYuntian commented on src/soc/sophgo/cv180x.h
> +void cv180Init(void);
```suggestion
void cv180xInit(void);
```
你都不编译测试一下么？

2024-03-13 10:33 UTC, RadxaYuntian requested changes

2024-03-13 10:33 UTC, RadxaYuntian commented on src/soc/sophgo/cv180x.c
> +#define UNKNOWN_COMMON_VALUES 0, {0x0, 0x0}, {GPIO_SWPORTA_DDR, 0}, {GPIO_SWPORTA_DR, 0}, FUNCTION_UNKNOWN, PINMODE_NOT_SET, 0
```suggestion
// register data currently unavailable
#define GPIO_UNAVAILABLE(x) ({x, 0, 0, {0, 0}, {0, 0}, {0, 0}, FUNCTION_UNKNOWN, 0, 0})
```
写宏的时候最好用括号包围，以免和其他部分的代码产生干扰
这里直接定义一个layout_t对象

2024-03-13 10:33 UTC, RadxaYuntian commented on src/soc/sophgo/cv180x.c
> +	{"UNKNOWN_XGPIOA_0", 0, UNKNOWN_COMMON_VALUES},
```suggestion
	GPIO_UNAVAILABLE("XGPIOA_0"),
```
名字暂时不用加前缀吧

2024-03-13 10:33 UTC, RadxaYuntian commented on src/soc/sophgo/cv180x.c
> +	if(pin->support == FUNCTION_UNKNOWN) {
这个检查要放在mapping == NULL之后，否则你会在前面的检查里使用非法参数

2024-03-13 11:47 UTC, RadxaYuntian approved these changes
commit squash一下后可以给上游提了

2024-03-13 11:52 UTC, closed without merging

2024-03-13 11:53 UTC, RadxaYuntian commented on src/soc/sophgo/cv180x.c
> +		wiringXLog(LOG_ERR, "The register of %s %s not open yet", cv180x->brand, cv180x->chip);
This pin is currently unavailable